# Generated by Django 5.2.4 on 2025-08-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0001_initial'),
        ('patients_diagnoses', '0001_initial'),
        ('therapists', '0001_initial'),
        ('histories_configurations', '0001_initial'),
    ]

    operations = [
        # Agregar campos como nullable primero
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='patients_diagnoses.patient',
                verbose_name='Paciente'
            ),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='therapists.therapist',
                verbose_name='Terapeuta'
            ),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_type',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='histories_configurations.paymenttype',
                verbose_name='Tipo de pago'
            ),
        ),
        migrations.AddField(
            model_name='ticket',
            name='appointment',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='appointments_status.appointment',
                verbose_name='Cita'
            ),
        ),
    ]
