# Generated by Django 5.2.4 on 2025-08-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_status', '0002_auto_20250821_1319'),
    ]

    operations = [
        # Hacer campos obligatorios después de tener datos
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='patients_diagnoses.patient',
                verbose_name='Paciente'
            ),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='therapists.therapist',
                verbose_name='Terapeuta'
            ),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='appointment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='appointments_status.appointment',
                verbose_name='Cita'
            ),
        ),
    ]
